-- Add all St. Louis area locations
INSERT INTO locations (name, slug, description, is_active, sort_order) VALUES
  ('St. Louis', 'st-louis', 'St. Louis city', true, 1),
  ('St. Louis County', 'st-louis-county', 'St. Louis County area', true, 2),
  ('Clayton', 'clayton', 'Clayton, MO', true, 3),
  ('University City', 'university-city', 'University City, MO', true, 4),
  ('Maplewood', 'maplewood', 'Maplewood, MO', true, 5),
  ('Richmond Heights', 'richmond-heights', 'Richmond Heights, MO', true, 6),
  ('Brentwood', 'brentwood', 'Brentwood, MO', true, 7),
  ('Webster Groves', 'webster-groves', 'Webster Groves, MO', true, 8),
  ('Kirkwood', 'kirkwood', 'Kirkwood, MO', true, 9),
  ('Creve Coeur', 'creve-coeur', 'Creve Coeur, MO', true, 10),
  ('Maryland Heights', 'maryland-heights', 'Maryland Heights, MO', true, 11),
  ('Hazelwood', 'hazelwood', 'Hazelwood, MO', true, 12),
  ('Florissant', 'florissant', 'Florissant, MO', true, 13),
  ('Ferguson', 'ferguson', 'Ferguson, MO', true, 14),
  ('Jennings', 'jennings', 'Jennings, MO', true, 15),
  ('Bellefontaine Neighbors', 'bellefontaine-neighbors', 'Bellefontaine Neighbors, MO', true, 16),
  ('Normandy', 'normandy', 'Normandy, MO', true, 17),
  ('Chesterfield', 'chesterfield', 'Chesterfield, MO', true, 18),
  ('Ballwin', 'ballwin', 'Ballwin, MO', true, 19),
  ('Ellisville', 'ellisville', 'Ellisville, MO', true, 20),
  ('Wildwood', 'wildwood', 'Wildwood, MO', true, 21),
  ('Eureka', 'eureka', 'Eureka, MO', true, 22),
  ('Pacific', 'pacific', 'Pacific, MO', true, 23),
  ('Valley Park', 'valley-park', 'Valley Park, MO', true, 24),
  ('Fenton', 'fenton', 'Fenton, MO', true, 25),
  ('Affton', 'affton', 'Affton, MO', true, 26),
  ('Lemay', 'lemay', 'Lemay, MO', true, 27),
  ('Mehlville', 'mehlville', 'Mehlville, MO', true, 28),
  ('Oakville', 'oakville', 'Oakville, MO', true, 29),
  ('Sunset Hills', 'sunset-hills', 'Sunset Hills, MO', true, 30),
  ('Sappington', 'sappington', 'Sappington, MO', true, 31),
  ('Crestwood', 'crestwood', 'Crestwood, MO', true, 32),
  ('Ladue', 'ladue', 'Ladue, MO', true, 33),
  ('Olivette', 'olivette', 'Olivette, MO', true, 34),
  ('Overland', 'overland', 'Overland, MO', true, 35),
  ('Bridgeton', 'bridgeton', 'Bridgeton, MO', true, 36),
  ('St. Ann', 'st-ann', 'St. Ann, MO', true, 37),
  ('Berkeley', 'berkeley', 'Berkeley, MO', true, 38),
  ('Ferguson', 'ferguson', 'Ferguson, MO', true, 39),
  ('Hazelwood', 'hazelwood', 'Hazelwood, MO', true, 40),
  ('Spanish Lake', 'spanish-lake', 'Spanish Lake, MO', true, 41),
  ('Moline Acres', 'moline-acres', 'Moline Acres, MO', true, 42),
  ('Riverview', 'riverview', 'Riverview, MO', true, 43),
  ('St. Charles', 'st-charles', 'St. Charles, MO', true, 44),
  ('St. Peters', 'st-peters', 'St. Peters, MO', true, 45),
  ('O''Fallon', 'ofallon', 'O''Fallon, MO', true, 46),
  ('Wentzville', 'wentzville', 'Wentzville, MO', true, 47),
  ('Lake St. Louis', 'lake-st-louis', 'Lake St. Louis, MO', true, 48),
  ('Cottleville', 'cottleville', 'Cottleville, MO', true, 49),
  ('Dardenne Prairie', 'dardenne-prairie', 'Dardenne Prairie, MO', true, 50),
  ('Weldon Spring', 'weldon-spring', 'Weldon Spring, MO', true, 51),
  ('East St. Louis', 'east-st-louis', 'East St. Louis, IL', true, 52),
  ('Belleville', 'belleville', 'Belleville, IL', true, 53),
  ('Fairview Heights', 'fairview-heights', 'Fairview Heights, IL', true, 54),
  ('Collinsville', 'collinsville', 'Collinsville, IL', true, 55),
  ('Edwardsville', 'edwardsville', 'Edwardsville, IL', true, 56)
ON CONFLICT (name) DO UPDATE SET 
  is_active = true,
  sort_order = EXCLUDED.sort_order;

-- Verify count
SELECT COUNT(*) as total_locations FROM locations WHERE is_active = true;
